import type { SupplierSeed, SupplierReviewSeed } from '../types.js'

export const suppliers: SupplierSeed[] = [
  { id: 'SUP-01', name: 'Asha Mehta', handle: '@ashamehta', location: 'Mumbai, India', country: 'India', verified: true, rating: 4.9, reviewCount: 214, productsAvailable: 68, responseTime: '~1h', memberSince: '2021', specialties: ['Prada', 'Gucci', 'Bottega Veneta'], bio: 'Mumbai-based personal shopper with long-standing relationships with boutiques and collectors. Every piece is hand-authenticated with provenance notes.', fulfillmentRate: 99, avatarHue: 150 },
  { id: 'SUP-02', name: 'Rohan Kapoor', handle: '@rohankapoor', location: 'New Delhi, India', country: 'India', verified: true, rating: 4.8, reviewCount: 189, productsAvailable: 52, responseTime: '~2h', memberSince: '2020', specialties: ['Chanel', 'Dior', 'Saint Laurent'], bio: 'Independent luxury buyer working with a small network of Delhi collectors. Particularly good at finding seasonal Chanel and hard-to-source Dior.', fulfillmentRate: 98, avatarHue: 32 },
  { id: 'SUP-03', name: 'Nandini Rao', handle: '@nandini.rao', location: 'Bengaluru, India', country: 'India', verified: true, rating: 5.0, reviewCount: 341, productsAvailable: 124, responseTime: '~40m', memberSince: '2019', specialties: ['Hermès', 'Chanel', 'Louis Vuitton'], bio: 'Collector and authenticator known for careful condition grading. Strongest on pristine vintage and rare Hermès leathers.', fulfillmentRate: 100, avatarHue: 6 },
  { id: 'SUP-04', name: 'Vikram Sethi', handle: '@vikram.sethi', location: 'Hyderabad, India', country: 'India', verified: true, rating: 4.7, reviewCount: 156, productsAvailable: 44, responseTime: '~3h', memberSince: '2021', specialties: ['Louis Vuitton', 'Celine', 'Fendi'], bio: 'Boutique consignment seller with a focus on modern classics and limited runway pieces. Ships across India from Hyderabad.', fulfillmentRate: 96, avatarHue: 214 },
  { id: 'SUP-05', name: 'Farah Khan', handle: '@farahkhan.luxe', location: 'Kochi, India', country: 'India', verified: true, rating: 4.9, reviewCount: 278, productsAvailable: 91, responseTime: '~1h', memberSince: '2020', specialties: ['Hermès', 'Chanel', 'Dior'], bio: 'Family-run luxury sourcing desk with a strong Gulf and India network. Exotics and full-set Hermès are a specialty.', fulfillmentRate: 97, avatarHue: 44 },
  { id: 'SUP-06', name: 'Arjun Malhotra', handle: '@arjun.malhotra', location: 'Pune, India', country: 'India', verified: false, rating: 4.5, reviewCount: 87, productsAvailable: 37, responseTime: '~5h', memberSince: '2022', specialties: ['Gucci', 'Prada', 'Bottega Veneta'], bio: 'Emerging seller with sharp pricing on current-season pieces. Verification is in progress.', fulfillmentRate: 92, avatarHue: 340 },
  { id: 'SUP-07', name: 'Meera Iyer', handle: '@meera.iyer', location: 'Chennai, India', country: 'India', verified: true, rating: 4.8, reviewCount: 203, productsAvailable: 59, responseTime: '~2h', memberSince: '2018', specialties: ['Chanel', 'Fendi', 'Celine'], bio: 'Archive and vintage specialist. Particularly good at finding 90s runway pieces with the paperwork to match.', fulfillmentRate: 95, avatarHue: 28 },
  { id: 'SUP-08', name: 'Kabir Bhatia', handle: '@kabir.bhatia', location: 'Chandigarh, India', country: 'India', verified: true, rating: 4.6, reviewCount: 132, productsAvailable: 40, responseTime: '~4h', memberSince: '2021', specialties: ['Louis Vuitton', 'Gucci', 'Saint Laurent'], bio: 'Independent reseller focused on reliable condition checks and quick domestic fulfilment. Strong on modern classics and everyday leather goods.', fulfillmentRate: 94, avatarHue: 220 },
  { id: 'SUP-09', name: 'Leena Thomas', handle: '@leenathomas', location: 'Goa, India', country: 'India', verified: false, rating: 4.4, reviewCount: 61, productsAvailable: 29, responseTime: '~6h', memberSince: '2023', specialties: ['Gucci', 'Prada'], bio: 'Leather-goods specialist building a small, carefully selected inventory of handbags and accessories.', fulfillmentRate: 90, avatarHue: 36 },
  { id: 'SUP-10', name: 'Sanjay Deshmukh', handle: '@sanjay.deshmukh', location: 'Ahmedabad, India', country: 'India', verified: true, rating: 4.9, reviewCount: 244, productsAvailable: 76, responseTime: '~1h', memberSince: '2019', specialties: ['Chanel', 'Hermès', 'Dior'], bio: 'Established sourcing desk with deep relationships across Indian collectors and overseas boutiques. Trusted by resellers nationwide.', fulfillmentRate: 98, avatarHue: 174 },
]

export const supplierReviews: SupplierReviewSeed[] = [
  { id: 'r1', supplierId: 'SUP-01', author: 'Ananya S.', rating: 5, date: '2026-08-30', body: 'Third order with Asha. The condition always matches the grade exactly and the paperwork is immaculate.' },
  { id: 'r2', supplierId: 'SUP-01', author: 'Kavya R.', rating: 5, date: '2026-08-12', body: 'Asha found a discontinued Bottega colourway in four days. Communication was excellent throughout.' },
  { id: 'r3', supplierId: 'SUP-01', author: 'Madhav P.', rating: 4, date: '2026-07-28', body: 'Great pieces. Shipping took a little longer than quoted, but everything arrived perfectly.' },
  { id: 'r4', supplierId: 'SUP-03', author: 'Sneha T.', rating: 5, date: '2026-09-01', body: 'Nandini grading is the gold standard. A very good from her beats an excellent from most desks.' },
  { id: 'r5', supplierId: 'SUP-03', author: 'Aarav B.', rating: 5, date: '2026-08-20', body: 'Rare Kelly in Etoupe, full set, exactly as described. I will only source Hermes here now.' },
  { id: 'r6', supplierId: 'SUP-02', author: 'Ishita G.', rating: 5, date: '2026-08-25', body: 'Rohan found me a seasonal Chanel flap the week it dropped. His boutique access is real.' },
  { id: 'r7', supplierId: 'SUP-05', author: 'Zoya M.', rating: 5, date: '2026-08-18', body: 'Same-day authentication as promised. Farah is my first call for anything exotic.' },
]
